### ISSUE TITLE
CVVor leading to unexpected results 

### ISSUE THREAD

**Issue by pyLP7** [FuhgJan/StateOfTheArtAdaptiveSampling#1]
I tested the 2D Rosenbrock function with the Cross-Validation-Voronoi (CVVor) method. After few iteration step, I got the result shown below:
![issue_CVVor_rosenbrock2D_](https://user-images.githubusercontent.com/73650883/137173540-11b7764e-1827-4f61-bef6-f52b65a81434.jpg)

As you can see from the orange circle highlighted in the contour plot, at some stage I got a sample very close to the starting 10 samples generated with TPLHD:
![voronoi_cell](https://user-images.githubusercontent.com/73650883/137175871-c94bfe65-f9c7-4625-ac50-758303788147.PNG)

If this were true, it would imply that the Voronoi region estimate is of very poor quality and its boundaries are completely wrong (very unlikely). 

I therefore believe that there is something that is not working out as expected. 
I look forward to hearing from you.

**Comment by FuhgJan** [comment]
Hi, thanks for bringing this to my attention!
I had uploaded an older version of CVVor with an error in it.

It is fixed now.
In the for loop of CVVor_function.m in line 26 the distance was not updated to find the maximum distance.

So by adding:
        maxDistance = distance;
to line 30 (which is now fixed in the newest version). It should work.

Let me know if you find any other mistakes.
Thanks a lot!
